# Welcome to Jekyll!
# Site settings

site_title: >-      # Site title
  小宝的博客 | XiaoBao Blog

title: XiaoBao Blog    # Site nav title
email: >-           # Site author email
  shenbaoone@gmail.com

icon: "/img/config/author-100.png"
description: >-     # Site description
  描述
keywords: >-        # Site keywords
  关键字
baseurl: "/xiaobao-blog"   # the subpath of your site, e.g. /blog
url: ""                           # site, e.g. http://example.com
  
site_url: https://shenbao.github.io
site_author:  ShenBao
creat_time: 2018


# twitter_username: jekyllrb
weibo_username:  ShenBaoPro
zhihu_username:  shenbao
github_username:  ShenBao
cnode_username:  ShenBao

disqus_username: ShenBao
hypercomments_userid: 91931

paginate: 2
paginate_path: "page:num"


markdown: kramdown # kramdown,redcarpet,rdiscount
kramdown:
input: GFM                            # use Github Flavored Markdown !important
highlighter: rouge
#permalink: pretty
exclude: ["node_modules","package.json","README.md",]


gems: [jekyll-paginate]

plugins:
  - jekyll-feed
  - jekyll-paginate












