# Welcome to Jekyll!
# Site settings

site_title: >-      # Site title
  小宝的博客 | XiaoBao Blog
title: XiaoBao Blog    # Site nav title
description: >-     # Site description
  小宝的博客 | XiaoBao Blog ,这是小宝的博客模板
keywords: >-        # Site keywords
  小宝的博客、XiaoBao Blog
icon: "/img/config/author-100.png"


site_url: https://shenbao.github.io
baseurl: "/xiaobao-blog"   # the subpath of your site, e.g. /blog
url: ""                           # site, e.g. http://example.com
site_author:  ShenBao
email: >-           # Site author email
  shenbaoone@gmail.com
creat_time: 2018

sidebar-about-icon: "/img/config/programmer.jpg"
sidebar-about-description: "少抱怨,多思考,未来更美好!"


# twitter_username: 
weibo_username:  ShenBaoPro
zhihu_username:  shenbao
github_username:  ShenBao
cnode_username:  ShenBao

disqus_username: ShenBao
hypercomments_userid: 91931

paginate: 5
paginate_path: "page:num"


markdown: kramdown # kramdown,redcarpet,rdiscount
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  highlighter: rouge
  syntax_highlighter: rouge
  highlight: true
  #permalink: pretty
  exclude: ["node_modules","package.json","README.md",]


plugins:
  - jekyll-feed
  - jekyll-paginate
